### ISSUE TITLE
Проблема с DNS сервером

### ISSUE THREAD

**Issue by DJTerentjev** [kvazis/training#6]
При выполнении sudo apt update зависало при обращении к archive.raspberrypi.org. Ping archive.raspberrypi.org тоже зависал. При этом ping google.com работал нормально. Сервер archive.raspberrypi.org пинговался без проблем с другого устройства этой локальной сети. Помогла смена DNS адреса на малинке. sudo nano /etc/resolv.conf и заменить адрес локального DNS сервера на 8.8.8.8. Это работает до перезагрузки. После установки network-manager первым DNS сервером вписать 8.8.8.8.
Видимо, вина роутера. Написал в Keenetic.

**Comment by goevs** [comment]
У меня была такая же проблема из-за того, что был включен протокол ipv6, после его отключения, всё заработало. 
P. S.
Такая проблема была только на одной малиновской ОС. С Ubuntu проблем не было, даже без отключения ipv6.

**Comment by goevs** [comment]
Роутер тоже кинетик
![Screenshot_20210301-132519_Keenetic.jpg](https://user-images.githubusercontent.com/40790796/109484823-f1c50680-7a91-11eb-9eeb-4707523373dc.jpg)

**Comment by DJTerentjev** [comment]
У меня Keenetic Giga II. Странно, мне отключение ipv6 не помогло. И пакет ipv6 и удалял и устанавливал.  Ничего не помогло. Посмотрим, что, Support ответит.

**Comment by DJTerentjev** [comment]
Вот что ответила поддержка Keenetic:  необходимо в настройках указать [DoT DoH сервера ](https://help.keenetic.com/hc/ru/articles/360007687159-%D0%9F%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D1%8B-DNS-over-TLS-%D0%B8-DNS-over-HTTPS-%D0%B4%D0%BB%D1%8F-%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-DNS-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%BE%D0%B2). После этого sudo apt update и т.д. заработало корректно
